CREATE ROLE anodiam_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'XXXXXXXX';

CREATE DATABASE anodiam
    WITH
    OWNER = anodiam_user
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

\c anodiam;

CREATE SCHEMA IF NOT EXISTS anodiam AUTHORIZATION anodiam_user;

CREATE TABLE IF NOT EXISTS anodiam.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS anodiam.roles
    OWNER to anodiam_user;

CREATE TABLE IF NOT EXISTS anodiam.signup_users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(50) COLLATE pg_catalog."default",
    first_name character varying(30) COLLATE pg_catalog."default",
    last_name character varying(30) COLLATE pg_catalog."default",
    password character varying(120) COLLATE pg_catalog."default",
    referer_email character varying(50) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    validation_token character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT signup_users_pkey PRIMARY KEY (id),
    CONSTRAINT signup_users_email_uk UNIQUE (email)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS anodiam.signup_users
    OWNER to anodiam_user;


CREATE TABLE IF NOT EXISTS anodiam.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(50) COLLATE pg_catalog."default",
    first_name character varying(30) COLLATE pg_catalog."default",
    last_name character varying(30) COLLATE pg_catalog."default",
    password character varying(120) COLLATE pg_catalog."default",
    referer_email character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_uk UNIQUE (email)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS anodiam.users
    OWNER to anodiam_user;

CREATE TABLE IF NOT EXISTS anodiam.user_roles
(
    email bigint NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (email, role_id),
    CONSTRAINT user_roles_email_fk FOREIGN KEY (email)
        REFERENCES anodiam.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT user_roles_role_id_fk FOREIGN KEY (role_id)
        REFERENCES anodiam.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS anodiam.user_roles
    OWNER to anodiam_user;