---
apiVersion: v1
kind: Secret
metadata:
  name: anodiam-secrets
type: Opaque
data:
  BCRYPT_SALT: Q29tcGxlI2FsdA==
  JWT_SECRET: Nm9tcGxlKjVlY3IzdA==
  DB_SECRET: QW5vZGlhbUAxMjM=
  SMTP_SECRET: eHNtdHBzaWItY2E1YmYzYmQyMTFmMjMyN2EyMTQzMWRjNTkwNTFjZDJkZWEyNzVlMmUwM2U5YmQzMzBmOTU2ZTg5OWViYzJlOC12VFZxQjZwS3pjR01DWkow